server:
  port: 8899

discord:
  user-token: '用户token'
  bot-token: '机器人token'
  server-id: '服务id'
  channel-id: '频道id'
call-back:
  url: '回调地址'

chatgpt:
  token: '用户token  chagpt的可以不填写'

wechat:
  token: 'gHKLFDFhahdkllsfjjshfkk'
  app_id: 'wxa06a131b64702c92'
  app_secret: '457dcc60e0c73ff48ef2eef52421bb1d'

# mongo
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/midjouney